export const data= [
    {
      "icon": "star_border",
      "icons2": "star_border",
      "title": "youtube",
      "message": "on Your Channel Future Coders",
      "decription": "on Your Channel Future Coders",
      "category" : "Placement",
  },
  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Placement",
  },
  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Placement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Placement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Placement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Placement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Placement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Placement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Announcement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Announcement",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Cultural",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Cultural",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Cultural",
  },  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Cultural",
  },
  {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Cultural",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Cultural",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Tech",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Tech",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Cultural",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Tech",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Tech",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Tech",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Tech",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Academics",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Academics",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Academics",
  }, {
  "icon": "star_border",
  "icons2": "star_border",
  "title": "youtube",
  "message": "on Your Channel Future Coders",
  "decription": "on Your Channel Future Coders",
  "category" : "Academics",
  },
  ];